package pk;
// Generated 11-oct-2016 22:01:04 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private String logonid;
     private String name;
     private String password;
     private String emailaddress;
     private Date lastlogon;

    public Users() {
    }

	
    public Users(String logonid) {
        this.logonid = logonid;
    }
    
    public Users(String logonid, String name, String password, String emailaddress, Date lastlogon) {
       this.logonid = logonid;
       this.name = name;
       this.password = password;
       this.emailaddress = emailaddress;
       this.lastlogon = lastlogon;
    }
   
    public String getLogonid() {
        return this.logonid;
    }
    
    public void setLogonid(String logonid) {
        this.logonid = logonid;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmailaddress() {
        return this.emailaddress;
    }
    
    public void setEmailaddress(String emailaddress) {
        this.emailaddress = emailaddress;
    }
    public Date getLastlogon() {
        return this.lastlogon;
    }
    
    public void setLastlogon(Date lastlogon) {
        this.lastlogon = lastlogon;
    }




}


