package model;
// Generated 12-oct-2016 18:44:49 by Hibernate Tools 4.3.1



/**
 * StockId generated by hbm2java
 */
public class StockId  implements java.io.Serializable {


     private int id;
     private int distribuidorId;

    public StockId() {
    }

    public StockId(int id, int distribuidorId) {
       this.id = id;
       this.distribuidorId = distribuidorId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getDistribuidorId() {
        return this.distribuidorId;
    }
    
    public void setDistribuidorId(int distribuidorId) {
        this.distribuidorId = distribuidorId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StockId) ) return false;
		 StockId castOther = ( StockId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getDistribuidorId()==castOther.getDistribuidorId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getDistribuidorId();
         return result;
   }   


}


